version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6.30-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/parallel-lint src
      - run: ./app/console lint:twig app
      - run: ./app/console lint:yaml app
      - run: ./bin/var-dump-check --ladybug --no-colors src
      - run: ./bin/php-cs-fixer fix --dry-run src
